import time

from selenium import webdriver
from selenium.webdriver.common.by import By

driver = webdriver.Chrome()
driver.get("https://www.nytimes.com/puzzles/spelling-bee")
driver.set_window_size(1680, 939)
time.sleep(30)  # Sleep for 30 seconds

# We know the letters for the day, but we need to find out how they're mapped
# to the javascript buttons, i.e. which letter is at which button

todays_letters = ""
for i in range(1, 8):
    todays_letters += driver.find_element(By.CSS_SELECTOR, ".hive-cell:nth-child(" + str(i) + ")").text


# Start looping through the possible combinations as generated by the BeeLister app
f = open("spellingbee_filename", "r")
for test_word in f:
    test_word = test_word.strip().upper()
    for letter_as_num_position in range(0, len(test_word)):
        position = todays_letters.find(test_word[letter_as_num_position])
        driver.find_element(By.CSS_SELECTOR, ".hive-cell:nth-child(" + str(position + 1) + ") > .cell-fill").click()
    driver.find_element(By.CSS_SELECTOR, ".hive-action__submit").click()
f.close()
